# Generated by Django 4.1.1 on 2022-09-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='desciption',
            new_name='group_desc',
        ),
    ]
