# Generated by Django 4.1.1 on 2022-09-20 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_group', '0005_alter_chatgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 20, 0, 3, 54, 515757, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
