# Generated by Django 4.1.1 on 2022-09-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_deletedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='deletedAt',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
